---
- hosts: localhost
  gather_facts: false
  vars:
    digital_ocean_token:' '
    droplet_size: s-1vcpu-1gb
    droplet_region: sgp1
    droplet_image: ubuntu-20-04-x64

  tasks:
    - name: Add public ssh key to Digital Ocean Account
      digital_ocean_sshkey:
        name: "Manjaro"
        oauth_token: "{{ digital_ocean_token }}"
        ssh_pub_key: "{{lookup('file', '~/.ssh/ocean.pub') }}"
        state: present
      register: sshkey_result

    - name: Creating a droplet using {{ droplet_image }}
      digital_ocean_droplet:
        name: v2rayvpn
        oauth_token: "{{ digital_ocean_token }}"
        size: "{{ droplet_size }}"
        region: "{{ droplet_region }}"
        image: "{{ droplet_image }} "
        wait_timeout: 600
        unique_name: yes
        ssh_keys: ["{{ sshkey_result.data.ssh_key.id }}"]
        state: present
      register: droplet_result

    - debug:
        msg: "Name is {{ droplet_result.data.droplet.name }} , IP is {{ droplet_result.data.ip_address }}"